version: "3.3"

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - static:/app/static/
      - media:/app/static/media/
    command: >
      bash -c "celery -A backend worker -l info -P eventlet &
                celery -A backend beat --loglevel=info"
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
